### ISSUE TITLE
PCDATA invalid Char value

### ISSUE THREAD

**Issue by pnorman** [ToeBee/ChangesetMD#20]
```
$ time python changesetmd.py -r -d changesets
latest sequence from the database: 1659606
latest sequence on OSM server: 1664404
server has new sequence. commencing replication
opening replication file at http://planet.osm.org/replication/changesets/001/659/607.osm.gz
Traceback (most recent call last):
  File "changesetmd.py", line 190, in <module>
    md.doReplication(conn)
  File "changesetmd.py", line 150, in doReplication
    self.parseFile(connection, self.fetchReplicationFile(currentSequence), True)
  File "changesetmd.py", line 72, in parseFile
    for action, elem in context:
  File "iterparse.pxi", line 207, in lxml.etree.iterparse.__next__ (src/lxml/lxml.etree.c:126122)
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 1, line 11, column 294
```

This is repeatable.

**Comment by pnorman** [comment]
If I view the XML in `less` I see `<text>The objects “light_minor” and “light_major” are simply lights without any details of the supporting structure. If you wish to specify the supporting structure, then you should use a seamark:type such as “beacon_special_purpose”, etc. Then you may specify its colour, shape, etc. ^AAlso, to specify a colour_pattern, there should be at least two colours.</text>`, where `^A` is highlighted as a control code.

**Comment by pnorman** [comment]
resolved in the api/replication.
