### ISSUE TITLE
Attempt to reconnect if necessary

### ISSUE THREAD

**Issue by pnorman** [ToeBee/ChangesetMD#4]
When performing an incremental update I got the following error:

```
Traceback (most recent call last):
  File "./changesetmd.py", line 77, in <module>
    parser.parse(args.fileName)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 304, in end_element
    self._cont_handler.endElement(name)
  File "/home/pnorman/osm/changesets/ChangesetMD/changesethandler.py", line 55, in endElement
    self.changeset.numChanges, self.changeset.userName,self.tags))
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

postgresql may of restarted during the skipping stage but it would be nice to not need to re-skip

**Comment by pnorman** [comment]
okay with it as is
